#!/usr/bin/env bash

if [ -n "$SFTP_IP" ]; then
  if [ -d world ]; then
    scp -i ${SFTP_KEYPATH} -r world/ ${SFTP_USER}@${SFTP_IP}:${SFTP_PATH}/world/
  else
    mkdir -p world
    cd world
    scp -i ${SFTP_KEYPATH} -r ${SFTP_USER}@${SFTP_IP}:${SFTP_PATH}/world/ world/
    cd ..
  fi
  rm .s3cfg
fi
